---
name: Code4LibLearningAsWeGoLandoWorkshopPrep
services:
  rubyserver:
    type: ruby:2.5
    build:
       - gem install bundler
    scanner: false
  phpserver:
    type: php:5.6
    scanner: false

  pythonserver:
    type: python:3.7
    scanner: false

  javaserver:
    type: tomcat:8
    scanner: false

  maven:
    type: compose
    app_mount: delegated
    services:
      image: maven:3.6.3-jdk-11
      command: tail -f /dev/null
    scanner: false

  db:
    type: mysql:5.7
    portforward: true
    creds:
      user: dba
      password: random
      database: not_prod
      scanner: false

tooling:
  mvn:
    service: maven
    cmd: mvn
