---
name: Code4LibLearningAsWeGoLandoWorkshopPrep
recipe: lamp
config:
  webroot: .
scanner: false

services:
  rubyserver:
    type: ruby:2.5
    build:
       - gem install bundler
    scanner: false

  pythonserver:
    type: python:3.7
    scanner: false

  javaserver:
    type: tomcat:8
    scanner: false

  maven:
    type: compose
    app_mount: delegated
    services:
      image: maven:3.6.3-jdk-11
      command: tail -f /dev/null
    build_as_root: apt install ant
    scanner: false

  node:
    type: node
    build:
      - npm install
      - gulp
    globals:
      gulp-cli: latest

tooling:
  mvn:
    service: maven
    cmd: mvn
  ant:
    service: maven
    cmd: ant
