---
name: Code4LibLearningAsWeGoLandoWorkshopPrep
recipe: lamp
config:
  webroot: .
scanner: false

services:
  rubyserver:
    type: ruby:2.5
    build:
      - gem install bundler
    scanner: false

  pythonserver:
    type: python:3.7
    scanner: false

  javaserver:
    type: tomcat:8
    scanner: false

  java:
    type: compose
    app_mount: delegated
    services:
      image: maven:3.6.3-jdk-11
      command: tail -f /dev/null
    build_as_root:
      - apt-get update -qq
      - apt install -y ant
    overrides:
      environment:
        M2_HOME: "/app/.m2"
        MAVEN_CONFIG: "/app/.m2"
    meUser: root
    scanner: false

  node:
    type: node
    build:
      - npm install
      # - gulp #uncomment this if there is a gulpfile in this project, otherwise gulp won't have anything to do
    globals:
      gulp-cli: latest
    scanner: false


tooling:
  mvn:
    service: java
    cmd: mvn
  ant:
    service: java
    cmd: ant
